masters = gentoo
repo-name = deftera
thin-manifests = true
sign-manifests = false
profile-formats = portage-2
cache-formats = md5-dict
manifest-hashes = BLAKE2B SHA512
manifest-required-hashes = BLAKE2B
properties-allowed = live
restrict-allowed = bindist fetch mirror network-sandbox strip test
